services:
  # --- CASSANDRA ---
  cassandra_iot1:
    image: cassandra:latest
    container_name: cassandra_iot1
    environment:
      - CASSANDRA_CLUSTER_NAME=DataPlatform
      - MAX_HEAP_SIZE=384M
      - HEAP_NEWSIZE=96M
      - CASSANDRA_NUM_TOKENS=16
      - JVM_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=20
    mem_limit: 768m
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -q UN"]
      interval: 30s
      timeout: 20s
      retries: 15
      start_period: 120s
    networks: [data-platform]

  cassandra_iot2:
    image: cassandra:latest
    container_name: cassandra_iot2
    depends_on:
      cassandra_iot1:
        condition: service_healthy
    environment:
      - CASSANDRA_CLUSTER_NAME=DataPlatform
      - CASSANDRA_SEEDS=cassandra_iot1
      - MAX_HEAP_SIZE=384M
      - HEAP_NEWSIZE=96M
      - CASSANDRA_NUM_TOKENS=16
      - JVM_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=20
    mem_limit: 768m
    networks: [data-platform]

  cassandra_iot3:
    image: cassandra:latest
    container_name: cassandra_iot3
    depends_on:
      cassandra_iot1:
        condition: service_healthy
    environment:
      - CASSANDRA_CLUSTER_NAME=DataPlatform
      - CASSANDRA_SEEDS=cassandra_iot1
      - MAX_HEAP_SIZE=384M
      - HEAP_NEWSIZE=96M
      - CASSANDRA_NUM_TOKENS=16
      - JVM_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=20
    mem_limit: 768m
    networks: [data-platform]

  # --- KAFKA & ZOOKEEPER ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: iot-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: "-Xms64M -Xmx128M"
    mem_limit: 180mb
    networks: [data-platform]

  iot-kafka-1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: iot-kafka-1
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://iot-kafka-1:29092,PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_HEAP_OPTS: "-Xms160M -Xmx160M"
    mem_limit: 300mb
    networks: [data-platform]

  iot-kafka-2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: iot-kafka-2
    depends_on: [zookeeper]
    ports: ["9093:9093"]
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://iot-kafka-2:29093,PLAINTEXT://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_HEAP_OPTS: "-Xms160M -Xmx160M"
    mem_limit: 300mb
    networks: [data-platform]

  iot-kafka-3:
    image: confluentinc/cp-kafka:7.4.0
    container_name: iot-kafka-3
    depends_on: [zookeeper]
    ports: ["9094:9094"]
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://iot-kafka-3:29094,PLAINTEXT://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_HEAP_OPTS: "-Xms160M -Xmx160M"
    mem_limit: 300mb
    networks: [data-platform]

  iot-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: iot-kafka-ui
    depends_on: [iot-kafka-1]
    ports: ["8080:8080"]
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: iot-kafka-1:29092,iot-kafka-2:29093,iot-kafka-3:29094
      JAVA_OPTS: "-Xms128M -Xmx180M"
    mem_limit: 220mb
    networks: [data-platform]


  iot_jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: iot_jupyter
    volumes:
      - ./airflow:/home/jovyan/airflow
      - ./data:/home/jovyan/data
      - ./notebooks:/home/jovyan/notebooks
      - ./models:/home/jovyan/models
    ports: ["8888:8888"]
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - PYSPARK_SUBMIT_ARGS=--driver-memory 512m --executor-memory 512m pyspark-shell
    mem_limit: 1000mb
    networks: [data-platform]

networks:
  data-platform:
    driver: bridge

volumes:
  postgres_data:
  superset-db-data:
  superset-redis-data:
  superset-packages: